// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5k-EdDY7MIXEgaE-5je8d28MO4cxb_54',
    appId: '1:511903832514:web:e40482f22d73df44011e5b',
    messagingSenderId: '511903832514',
    projectId: 'khan5743',
    authDomain: 'khan5743.firebaseapp.com',
    storageBucket: 'khan5743.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-2gh3L2fVZ5VBWT-5umZiXTsuAJky-hM',
    appId: '1:511903832514:android:c5d0d2af619c7eae011e5b',
    messagingSenderId: '511903832514',
    projectId: 'khan5743',
    storageBucket: 'khan5743.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5k-EdDY7MIXEgaE-5je8d28MO4cxb_54',
    appId: '1:511903832514:web:ed2502bb4074cdee011e5b',
    messagingSenderId: '511903832514',
    projectId: 'khan5743',
    authDomain: 'khan5743.firebaseapp.com',
    storageBucket: 'khan5743.firebasestorage.app',
  );
}
